-- Generated by scripts/geocode_restaurants.py on 2026-05-14
-- Backfill lat/lng/kakao_place_id for restaurants inserted in 20260514120004_real_data.sql
-- Idempotent: same UPDATE applied repeatedly is safe.

BEGIN;

-- August 8 Chicken -> 어거스트치킨 본점 (서울 서초구 방배로 140) d=3643m
UPDATE restaurants SET lat=37.4864945, lng=126.9947581, kakao_place_id='1180498646' WHERE id='af95db27-8c45-52da-8326-747dea876bfb';
-- PPK키친 -> 피피케이키친 양재점 (서울 강남구 남부순환로359길 14) d=256m
UPDATE restaurants SET lat=37.4859240, lng=127.0366455, kakao_place_id='305687283' WHERE id='789b7040-570a-5cb7-aff0-6881a3ee5cce';
-- 갈비사랑 -> 갈비사랑 (서울 서초구 강남대로 204) d=157m
UPDATE restaurants SET lat=37.4824263, lng=127.0366754, kakao_place_id='216902976' WHERE id='dc879097-b34f-5f2a-a68e-76f4b9732ac9';
-- 강남회춘식당  [뱅뱅사거리] -> 회춘식당 (서울 강남구 강남대로62길 14) d=789m
UPDATE restaurants SET lat=37.4903176, lng=127.0326821, kakao_place_id='441374620' WHERE id='0c9a7af7-fbb6-5bff-b033-a8cc56108aea';
-- 강촌쭈꾸미 -> 강촌원조쭈꾸미 본점 (서울 서초구 남부순환로350길 36) d=46m
UPDATE restaurants SET lat=37.4833544, lng=127.0361953, kakao_place_id='13291936' WHERE id='156197fc-8142-5729-83cb-a9dccfdbd36d';
-- 금이네 -> 금이네 (서울 서초구 바우뫼로41길 16) d=548m
UPDATE restaurants SET lat=37.4812994, lng=127.0413240, kakao_place_id='600128318' WHERE id='2e863320-8c2c-5c47-94f0-058b6c09779f';
-- 넛츠비어 -> 넛츠비어 양재역점 (서울 서초구 남부순환로347길 20) d=397m
UPDATE restaurants SET lat=37.4853172, lng=127.0318850, kakao_place_id='1687057863' WHERE id='383c351e-b73d-5073-a354-d589788cc6ec';
-- 노상치킨 -> 베트남노상식당 강남점 (서울 강남구 역삼로 234) d=1591m
UPDATE restaurants SET lat=37.4971018, lng=127.0422102, kakao_place_id='155242459' WHERE id='b49a2a88-166e-5d51-ad22-233cb7b67f43';
-- 디오디아2.0 -> 디오디아2.0 (서울 서초구 강남대로 213) d=151m
UPDATE restaurants SET lat=37.4823536, lng=127.0356646, kakao_place_id='7850610' WHERE id='4f3c5528-d391-59ab-b78a-83e61b73b39a';
-- 뚝배기 양평해장국 -> 뚝배기양평해장국 양재점 (서울 서초구 강남대로30길 68) d=460m
UPDATE restaurants SET lat=37.4826348, lng=127.0409335, kakao_place_id='1128846505' WHERE id='9618acfc-5892-534b-aa91-972be9294fec';
-- 라그릴리아 양재점 -> 라그릴리아 양재점 (서울 서초구 남부순환로 2620) d=156m
UPDATE restaurants SET lat=37.4845317, lng=127.0373209, kakao_place_id='18373278' WHERE id='107696b0-daec-597d-ab9f-c4f7bb31cb92';
-- 로마옥 -> 로마옥 도곡 (서울 강남구 강남대로48길 11) d=398m
UPDATE restaurants SET lat=37.4869726, lng=127.0340849, kakao_place_id='237005010' WHERE id='b3e62e1a-d4ce-5fe9-b7b8-77e4b9199031';
-- 생활맥주 -> 생활맥주 양재점 (서울 서초구 남부순환로356길 42) d=210m
UPDATE restaurants SET lat=37.4830718, lng=127.0381478, kakao_place_id='27443961' WHERE id='84b2ef47-6ce8-5278-9143-c323ab244fa3';
-- 석암생소금구이 -> 석암생소금구이 양재점 (서울 서초구 강남대로 222-6) d=21m
UPDATE restaurants SET lat=37.4838276, lng=127.0357309, kakao_place_id='1216924554' WHERE id='eea05ee4-c89c-53ac-8481-4406395d6df8';
-- 소신 -> 소신 (서울 서초구 강남대로30길 65) d=443m
UPDATE restaurants SET lat=37.4828078, lng=127.0407889, kakao_place_id='1521608712' WHERE id='50f5ee59-ed72-585b-9b3f-a0c2751be8c3';
-- 아리노마마 -> 아리노 마마 (서울 강남구 남부순환로 2615) d=165m
UPDATE restaurants SET lat=37.4851809, lng=127.0358762, kakao_place_id='18384838' WHERE id='667253f1-a968-57a4-9477-49fbb93a60a8';
-- 아웃백 스테이크 -> 아웃백스테이크하우스 양재점 (서울 서초구 남부순환로 2567) d=427m
UPDATE restaurants SET lat=37.4844164, lng=127.0311497, kakao_place_id='932404631' WHERE id='f6a13093-e6e5-5e58-a288-93592736335a';
-- 야끼토리 나루토 [강남역] -> 야키토리 나루토 (서울 마포구 독막로9길 26) d=12546m
UPDATE restaurants SET lat=37.5493541, lng=126.9202080, kakao_place_id='747903409' WHERE id='4c4b619c-c103-5ffb-a26c-246329894122';
-- 양계옥 -> 양계옥 (서울 강남구 남부순환로 2615) d=165m
UPDATE restaurants SET lat=37.4851854, lng=127.0358842, kakao_place_id='427153962' WHERE id='0f5b552b-0d67-59b8-bcd2-568a015139bd';
-- 양재닭집 -> 양재닭집 (서울 서초구 남부순환로350길 25) d=27m
UPDATE restaurants SET lat=37.4837320, lng=127.0361989, kakao_place_id='2091770834' WHERE id='907991b2-b15a-5eea-b970-d3bf025b5d42';
-- 양재치킨 -> 양재닭집 (서울 서초구 남부순환로350길 25) d=27m
UPDATE restaurants SET lat=37.4837320, lng=127.0361989, kakao_place_id='2091770834' WHERE id='aacbccc1-d602-5143-91df-73dc7e74a323';
-- 역전할머니맥주 -> 역전할머니맥주 서울양재말죽거리점 (서울 서초구 남부순환로356길 39) d=233m
UPDATE restaurants SET lat=37.4832393, lng=127.0384781, kakao_place_id='1856854790' WHERE id='0f6194f1-50d1-5189-9b8e-b2925ad07876';
-- 영동족발 -> 영동족발 본점 (서울 서초구 남부순환로358길 8) d=209m
UPDATE restaurants SET lat=37.4845657, lng=127.0380050, kakao_place_id='23985599' WHERE id='93ac2712-b20e-523d-a753-0939cab8a93a';
-- 오부찌 -> 오부찌 양재점 (서울 서초구 강남대로41길 13) d=514m
UPDATE restaurants SET lat=37.4869480, lng=127.0317613, kakao_place_id='1113709894' WHERE id='2ff69c64-8423-50e4-a6a3-790417fb40c8';
-- 오징어회세꼬시 -> 오징어회세꼬시 (서울 서초구 남부순환로356길 74) d=324m
UPDATE restaurants SET lat=37.4816553, lng=127.0385180, kakao_place_id='24975678' WHERE id='446f1003-516e-5269-8e4f-09a9a697b07c';
-- 옥된장 -> 옥된장 양재점 (서울 서초구 서운로6길 29) d=488m
UPDATE restaurants SET lat=37.4857724, lng=127.0310191, kakao_place_id='258034127' WHERE id='ec5c54f8-1c29-5965-a6c1-8bca293d9776';
-- 우나유 -> 우나유 (서울 서초구 서운로11길 35) d=908m
UPDATE restaurants SET lat=37.4873953, lng=127.0267220, kakao_place_id='2126313537' WHERE id='017ebb18-0b98-5543-bd88-d439f7679933';
-- 우연술상 -> 우연술상 (서울 서초구 남부순환로356길 32) d=186m
UPDATE restaurants SET lat=37.4834710, lng=127.0379830, kakao_place_id='84465105' WHERE id='f2f9d5e5-5d9a-575c-ae68-2bfbb42758aa';
-- 이가네 양꼬치 -> 이가네양꼬치 양재역직영점 (서울 강남구 남부순환로351길 8) d=213m
UPDATE restaurants SET lat=37.4853984, lng=127.0347807, kakao_place_id='322986802' WHERE id='f5830bb9-c8b7-5177-8717-a3abe05660a4';
-- 이층완우 -> 이층완우 (서울 서초구 남부순환로356길 18-5) d=151m
UPDATE restaurants SET lat=37.4840298, lng=127.0375604, kakao_place_id='1925023149' WHERE id='c47bcbd2-4894-51cc-b839-70586fd0d8a3';
-- 자인뭉티기 -> 자인뭉티기 (서울 서초구 강남대로37길 24-7) d=371m
UPDATE restaurants SET lat=37.4851820, lng=127.0321337, kakao_place_id='9412618' WHERE id='6b9a6013-8dfb-5501-bda2-715613c8dc59';
-- 장수정육식당 -> 장수정육식당 (서울 서초구 남부순환로 2581-5) d=313m
UPDATE restaurants SET lat=37.4848214, lng=127.0326492, kakao_place_id='1998189483' WHERE id='02bbbbd4-39e6-5791-879e-7d3a3b194851';
-- 정고기 -> 정고기 (서울 서초구 강남대로34길 43) d=207m
UPDATE restaurants SET lat=37.4837899, lng=127.0382398, kakao_place_id='1391868748' WHERE id='e6550e75-63f3-5ab6-a773-fb76b4793282';
-- 젠부닥 -> 잰부닥 (서울 강남구 강남대로42길 13) d=206m
UPDATE restaurants SET lat=37.4854298, lng=127.0350781, kakao_place_id='19215962' WHERE id='97a55a86-0a3c-5c38-af5c-96afe0fcd05b';
-- 지우네 [뱅뱅사거리] -> 지우네 (서울 강남구 강남대로62길 12) d=796m
UPDATE restaurants SET lat=37.4903248, lng=127.0324808, kakao_place_id='186040653' WHERE id='677b3665-35fa-566a-8954-3762c50c418d';
-- 진스시 -> 진스시 (서울 서초구 강남대로43길 22-2) d=599m
UPDATE restaurants SET lat=37.4875249, lng=127.0311216, kakao_place_id='27082190' WHERE id='e1204274-349f-58cf-8229-17ab5bc04585';
-- 진여사댁 -> 진여사댁 (서울 서초구 강남대로34길 38) d=179m
UPDATE restaurants SET lat=37.4835494, lng=127.0379163, kakao_place_id='1539389679' WHERE id='efb14207-804b-55a2-982d-e35b57a8c74d';
-- 치킨영토 -> 치킨영토 양재점 (서울 서초구 남부순환로350길 29-3) d=35m
UPDATE restaurants SET lat=37.4836085, lng=127.0362825, kakao_place_id='2072531633' WHERE id='57c95856-8873-5795-a658-d0d755b72389';
-- 쿠파 -> 쿠파 (서울 서초구 남부순환로356길 51) d=256m
UPDATE restaurants SET lat=37.4827077, lng=127.0385230, kakao_place_id='717223378' WHERE id='e853f81f-5e28-5834-ad92-55c35a8d13f3';
-- 텍사스데브라질[고터] -> 텍사스데브라질 압구정점 (서울 강남구 논현로 854) d=4669m
UPDATE restaurants SET lat=37.5253208, lng=127.0288657, kakao_place_id='1248615345' WHERE id='228d0020-54a2-5c35-a718-ed7d3808fa60';
-- 펍피맥 -> 펍피맥 양재점 (서울 서초구 남부순환로356길 50) d=233m
UPDATE restaurants SET lat=37.4827789, lng=127.0382754, kakao_place_id='596683130' WHERE id='c23eed7f-d533-5134-8969-d51a89aa20b1';
-- KFC -> KFC 양재동점 (서울 서초구 남부순환로350길 4) d=104m
UPDATE restaurants SET lat=37.4844423, lng=127.0351907, kakao_place_id='10994102' WHERE id='9cf78b71-75c9-59ed-ae7f-2f3f273f951e';
-- 강남돈가스 -> 153구포국수 양재역점 (서울 강남구 남부순환로 2615) d=149m
UPDATE restaurants SET lat=37.4850367, lng=127.0358174, kakao_place_id='1680930595' WHERE id='f3452151-0a9e-5a57-a4fc-c4c47b9729b3';
-- 강촌쭈꾸미 -> 강촌원조쭈꾸미 본점 (서울 서초구 남부순환로350길 36) d=46m
UPDATE restaurants SET lat=37.4833544, lng=127.0361953, kakao_place_id='13291936' WHERE id='fd427f51-48ca-53b6-aa14-a84cd3193764';
-- 개수리막국수 -> 개수리막국수 강남도곡점 (서울 강남구 남부순환로365길 5) d=378m
UPDATE restaurants SET lat=37.4858087, lng=127.0392550, kakao_place_id='2005623669' WHERE id='cfe4673b-9e95-530c-aba4-2825dc69f071';
-- 고려향 -> 고려향 (서울 서초구 강남대로 156-1) d=613m
UPDATE restaurants SET lat=37.4787827, lng=127.0390501, kakao_place_id='704188840' WHERE id='8313c85a-8d15-542a-a6dc-3a9ca00189c2';
-- 고화갈비살 -> 고화갈비살 (경기 성남시 분당구 판교역로192번길 16) d=11665m
UPDATE restaurants SET lat=37.3976452, lng=127.1114731, kakao_place_id='1749260985' WHERE id='fcfb74b6-587f-5a7e-844c-a21d49e216f7';
-- 곱창왕김형제 -> 곱창왕김형제 양재본점 (서울 강남구 강남대로 240) d=202m
UPDATE restaurants SET lat=37.4851993, lng=127.0346031, kakao_place_id='772858218' WHERE id='6894b024-c700-5dcf-a988-dddb629ee18c';
-- 난랑 -> 난랑 서초점 (서울 서초구 서운로 32) d=695m
UPDATE restaurants SET lat=37.4869631, lng=127.0291777, kakao_place_id='12754010' WHERE id='fca63310-3a53-5e15-b3aa-8be38b15d232';
-- 도라지국수집 -> 도라지국수 (서울 서초구 남부순환로356길 15) d=188m
UPDATE restaurants SET lat=37.4841873, lng=127.0379392, kakao_place_id='377935945' WHERE id='1a10cc9b-6207-5a63-9514-fd22e2102c9b';
-- 도화 -> 도화 (서울 서초구 서운로6길 22) d=522m
UPDATE restaurants SET lat=37.4856707, lng=127.0305272, kakao_place_id='1898111480' WHERE id='46244802-ceb9-529a-8608-f3e176f85a40';
-- 돈까스하우스 -> 돈까스하우스 (서울 강남구 남부순환로359길 16) d=264m
UPDATE restaurants SET lat=37.4860078, lng=127.0365811, kakao_place_id='807181905' WHERE id='20533954-04ad-5ec3-9534-e68a1c6e4cdb';
-- 뚝배기 양평해장국 -> 뚝배기양평해장국 양재점 (서울 서초구 강남대로30길 68) d=460m
UPDATE restaurants SET lat=37.4826348, lng=127.0409335, kakao_place_id='1128846505' WHERE id='6b32291c-7981-5145-8b86-284d01b21dc6';
-- 롯데리아 -> 롯데리아 양재역점 (서울 서초구 강남대로 206) d=117m
UPDATE restaurants SET lat=37.4827165, lng=127.0363816, kakao_place_id='1540627030' WHERE id='a736378e-d879-5eb4-bf26-0654dca15cef';
-- 마성떡볶이 -> 마성떡볶이 양재역점 (서울 서초구 남부순환로 지하 2585) d=122m
UPDATE restaurants SET lat=37.4839352, lng=127.0345437, kakao_place_id='1877657113' WHERE id='8c4f3112-8416-5810-8145-82ab9c5dae3e';
-- 마차이짬뽕 -> 마차이짬뽕 양재역점 (서울 서초구 남부순환로 2579) d=300m
UPDATE restaurants SET lat=37.4846304, lng=127.0327079, kakao_place_id='1457439855' WHERE id='b6825012-5a9c-56d2-9a83-67c154b2b1c5';
-- 만두랑 -> 싸다김밥 양재역점 (서울 서초구 강남대로 212) d=68m
UPDATE restaurants SET lat=37.4830905, lng=127.0359827, kakao_place_id='1862124437' WHERE id='e7080953-849d-550e-92b6-0fa5785751f0';
-- 만복국수집 -> 만복집 양재점 (서울 서초구 남부순환로350길 19-10) d=45m
UPDATE restaurants SET lat=37.4839301, lng=127.0363211, kakao_place_id='12964891' WHERE id='c54253bf-ee9e-5b58-846e-c59aee935fed';
-- 맥도날드 -> 맥도날드 양재점 (서울 서초구 강남대로 213) d=153m
UPDATE restaurants SET lat=37.4823229, lng=127.0358240, kakao_place_id='10349441' WHERE id='22faeb75-a615-5708-8385-a8908a2f3fed';
-- 멘츠루 -> 멘츠루 양재점 (서울 서초구 강남대로37길 26) d=361m
UPDATE restaurants SET lat=37.4849882, lng=127.0321506, kakao_place_id='811739187' WHERE id='08800122-8a24-5cb4-8e04-d240e976cbd2';
-- 명갈비곰탕 -> 명갈비곰탕 (서울 서초구 서운로6길 26) d=492m
UPDATE restaurants SET lat=37.4855364, lng=127.0308257, kakao_place_id='1886399664' WHERE id='0d436e68-0c23-5b7e-b208-58b2ec9089f8';
-- 미가참치 -> 미가참치 (서울 서초구 남부순환로350길 13) d=49m
UPDATE restaurants SET lat=37.4841267, lng=127.0357853, kakao_place_id='12065822' WHERE id='486162ad-4b27-5f8c-bbcf-9cc7ac4226eb';
-- 미몽 -> 미몽 양재본점 (서울 서초구 강남대로34길 27-4) d=139m
UPDATE restaurants SET lat=37.4835496, lng=127.0374674, kakao_place_id='1210437091' WHERE id='761d908d-197d-5c60-a774-0809ae9fceb5';
-- 백소정 -> 백소정 양재역점 (서울 서초구 남부순환로347길 23) d=433m
UPDATE restaurants SET lat=37.4854254, lng=127.0315040, kakao_place_id='844904579' WHERE id='fb24076a-58c5-5e25-9e56-bdeb23217af7';
-- 백채김치찌개 -> 백채김치찌개 양재역점 (서울 서초구 남부순환로356길 37) d=217m
UPDATE restaurants SET lat=37.4833348, lng=127.0383198, kakao_place_id='2092446722' WHERE id='24c34a9d-b758-5a0f-97dc-d5b2f68048ee';
-- 버거킹 -> 버거킹 양재점 (서울 서초구 서초동 1376-21) d=170m
UPDATE restaurants SET lat=37.4840371, lng=127.0340214, kakao_place_id='7900896' WHERE id='2139f3ba-66be-56a7-abd9-275b5233da85';
-- 보글이 생태탕 왕코다리 -> 보글이생태탕왕코다리 양재역점 (서울 서초구 강남대로37길 56-18) d=510m
UPDATE restaurants SET lat=37.4854554, lng=127.0305645, kakao_place_id='1233001797' WHERE id='de2ae0a9-f749-5f1a-bf8a-c2435a298ef5';
-- 부강옥 -> 부강옥 서초 양재본점 (서울 서초구 논현로31길 14) d=569m
UPDATE restaurants SET lat=37.4819965, lng=127.0419778, kakao_place_id='665824227' WHERE id='022826c6-f77d-57ac-8917-39f7cac18cf8';
-- 부대옥 -> 부대옥 양재역점 (서울 서초구 남부순환로 2614) d=112m
UPDATE restaurants SET lat=37.4845770, lng=127.0365317, kakao_place_id='362732742' WHERE id='e5d582bb-66e9-5fb9-b5b0-c4c305d5769e';
-- 삼산회관 -> 삼산회관 양재본점 (서울 서초구 남부순환로356길 39) d=229m
UPDATE restaurants SET lat=37.4832186, lng=127.0384193, kakao_place_id='1142272706' WHERE id='5cf03eb3-7636-5484-b3be-5bc86ec334c3';
-- 새우닭 -> 새우닭 양재역점 (서울 서초구 남부순환로356길 52) d=249m
UPDATE restaurants SET lat=37.4825672, lng=127.0383285, kakao_place_id='1708719409' WHERE id='b3fa5e62-d8ba-5415-94c9-40ab74ad1021';
-- 샹차이 -> 샹차이 (서울 서초구 강남대로34길 76) d=367m
UPDATE restaurants SET lat=37.4839632, lng=127.0400512, kakao_place_id='24768787' WHERE id='daf4a5f8-72bf-511c-996f-b5b6ab21c156';
-- 서브웨이 -> 써브웨이 양재역점 (서울 서초구 남부순환로 2606) d=94m
UPDATE restaurants SET lat=37.4845439, lng=127.0357742, kakao_place_id='1454527924' WHERE id='2031118f-6ebd-5645-bcc7-6e588dcfe616';
-- 성심식당 -> 성심식당 (서울 서초구 바우뫼로41길 13) d=537m
UPDATE restaurants SET lat=37.4811157, lng=127.0410412, kakao_place_id='1024508071' WHERE id='1379fa11-ad55-5ad3-a0ad-6108ebe7335d';
-- 세광양대창 -> 세광양대창 양재점 (서울 서초구 강남대로 222-6) d=21m
UPDATE restaurants SET lat=37.4838294, lng=127.0357286, kakao_place_id='1326153988' WHERE id='85b3201a-9686-5364-bdb3-537248668ed7';
-- 소풍 -> 소풍 양재점 (서울 서초구 남부순환로347길 13) d=398m
UPDATE restaurants SET lat=37.4849613, lng=127.0316814, kakao_place_id='760548555' WHERE id='4602effd-259a-545a-800e-1e7c4a7805c0';
-- 손수동 -> 손수동 (서울 서초구 강남대로34길 33) d=157m
UPDATE restaurants SET lat=37.4836099, lng=127.0376811, kakao_place_id='193773470' WHERE id='1dbf4eea-9674-5fd0-a9dc-38212df56776';
-- 쇼쿠지 -> 쇼쿠지 양재점 (서울 서초구 서운로6길 19) d=532m
UPDATE restaurants SET lat=37.4858960, lng=127.0305420, kakao_place_id='1565116350' WHERE id='e9759914-f149-576d-821a-aa35250590b6';
-- 순대일번지 -> 순대일번지 양재점 (서울 서초구 남부순환로350길 11) d=65m
UPDATE restaurants SET lat=37.4842799, lng=127.0357741, kakao_place_id='788681423' WHERE id='3c96335d-e62a-50a0-8849-0f1f86f9768e';
-- 스파게티스토리 -> 스파게티스토리 (서울 강남구 남부순환로359길 20) d=279m
UPDATE restaurants SET lat=37.4861646, lng=127.0364986, kakao_place_id='14928984' WHERE id='1549beac-6be7-5c79-baa2-b83329b148bc';
-- 식겁라면순두부 -> 이광진식겁라면순두부 도곡점 (서울 강남구 남부순환로361길 6) d=252m
UPDATE restaurants SET lat=37.4855426, lng=127.0375634, kakao_place_id='19011066' WHERE id='11b79222-9552-5964-8a73-41449b87d259';
-- 신 사골 해장국 -> 신사골감자탕 양재점 (서울 강남구 강남대로 242) d=246m
UPDATE restaurants SET lat=37.4853733, lng=127.0340831, kakao_place_id='241426052' WHERE id='672a2c29-ac5c-5a98-84ab-062ebd471514';
-- 싸다김밥 양재역 -> 싸다김밥 양재역점 (서울 서초구 강남대로 212) d=68m
UPDATE restaurants SET lat=37.4830905, lng=127.0359827, kakao_place_id='1862124437' WHERE id='5bc70069-8c8b-51f0-a7ed-1ce299d6c41e';
-- 양재 오제섞어 -> 양재오제섞어 양재본점 (서울 서초구 바우뫼로41길 8) d=573m
UPDATE restaurants SET lat=37.4810605, lng=127.0414832, kakao_place_id='661927676' WHERE id='641d022c-fac0-53ec-a466-4e0bf269023c';
-- 양재동 김밥 -> 싸다김밥 양재역점 (서울 서초구 강남대로 212) d=68m
UPDATE restaurants SET lat=37.4830905, lng=127.0359827, kakao_place_id='1862124437' WHERE id='341341b9-19cc-5ed0-8d0f-9d5acbf75eae';
-- 양재순대 -> 순대일번지 양재점 (서울 서초구 남부순환로350길 11) d=65m
UPDATE restaurants SET lat=37.4842799, lng=127.0357741, kakao_place_id='788681423' WHERE id='44bbb05a-d76f-5af8-8207-8950040e7ec5';
-- 양재옥 -> 안산 양재옥 (경기 안산시 상록구 해양3로 15) d=28665m
UPDATE restaurants SET lat=37.2857487, lng=126.8280624, kakao_place_id='221043875' WHERE id='47547762-4d86-51c4-a1da-fb87e842e6d1';
-- 오부찌 -> 오부찌 양재점 (서울 서초구 강남대로41길 13) d=514m
UPDATE restaurants SET lat=37.4869480, lng=127.0317613, kakao_place_id='1113709894' WHERE id='a400563d-1c55-540e-88a6-c21b865384a6';
-- 오양지 -> 오양지 양재본점 (서울 서초구 남부순환로350길 19-6) d=31m
UPDATE restaurants SET lat=37.4838752, lng=127.0361764, kakao_place_id='160273589' WHERE id='ee1ad6bb-323b-5531-aeaf-dec880fef7c9';
-- 왕돈까스&왕냉면 양재점 -> 왕냉면앤왕까스 양재점 (서울 서초구 강남대로34길 38) d=184m
UPDATE restaurants SET lat=37.4835512, lng=127.0379762, kakao_place_id='15632656' WHERE id='dea66e48-4f13-530e-b80e-a2d33a5948bd';
-- 이조갈비 -> 이조갈비탕 (서울 서초구 양재천로19길 48) d=722m
UPDATE restaurants SET lat=37.4774585, lng=127.0381518, kakao_place_id='453534765' WHERE id='4b57b9ad-9590-54f0-8abd-edf648da6da9';
-- 이층완우 -> 이층완우 (서울 서초구 남부순환로356길 18-5) d=151m
UPDATE restaurants SET lat=37.4840298, lng=127.0375604, kakao_place_id='1925023149' WHERE id='140c85be-ab6b-5a27-9edb-814500efc7d1';
-- 인덕원비빔국수 -> 인덕원비빔국수 (서울 서초구 남부순환로 2656) d=485m
UPDATE restaurants SET lat=37.4852270, lng=127.0410502, kakao_place_id='1232624597' WHERE id='d439b5e9-2147-51c5-8e09-ce9f9614e233';
-- 임병주산동칼국수 -> 임병주 산동칼국수 (서울 서초구 강남대로37길 65) d=527m
UPDATE restaurants SET lat=37.4845698, lng=127.0300304, kakao_place_id='25038356' WHERE id='c4bbbb42-216e-53ca-ae6c-a445ea520b69';
-- 장금수 부대찌개 -> 장금수부대찌개 양재점 (서울 서초구 강남대로30길 73-3) d=461m
UPDATE restaurants SET lat=37.4828339, lng=127.0410071, kakao_place_id='1908094191' WHERE id='3944c280-a4cd-5b7f-8244-ce55659674d6';
-- 장수정육식당 -> 장수정육식당 (서울 서초구 남부순환로 2581-5) d=313m
UPDATE restaurants SET lat=37.4848214, lng=127.0326492, kakao_place_id='1998189483' WHERE id='74f199ab-017c-5c50-88d8-8d4df7c72b58';
-- 정고기 -> 정고기 (서울 서초구 강남대로34길 43) d=207m
UPDATE restaurants SET lat=37.4837899, lng=127.0382398, kakao_place_id='1391868748' WHERE id='a12761f4-0f38-55a1-b0a0-bc7c3f64f8d8';
-- 정성순대 -> 정성순대 (부산 연제구 중앙대로 1116-5) d=314291m
UPDATE restaurants SET lat=35.1872587, lng=129.0818804, kakao_place_id='563484966' WHERE id='7ec69c44-f393-5451-b8cd-2cec92218782';
-- 진순대 양재역점(강창구) -> 강창구찹쌀진순대 양재역점 (서울 서초구 강남대로34길 8) d=115m
UPDATE restaurants SET lat=37.4828668, lng=127.0366666, kakao_place_id='32010788' WHERE id='03763e54-ff17-5f2f-a834-2ca82c6aba60';
-- 진여사댁 -> 진여사댁 (서울 서초구 강남대로34길 38) d=179m
UPDATE restaurants SET lat=37.4835494, lng=127.0379163, kakao_place_id='1539389679' WHERE id='dae47b02-684f-5db5-b9cd-1a8189391704';
-- 찌개집1979 -> 찌개집1979 양재역점 (서울 강남구 강남대로 240) d=217m
UPDATE restaurants SET lat=37.4852597, lng=127.0344302, kakao_place_id='1156425526' WHERE id='2887fdb4-01ae-5bd1-a3bb-c485ff9f1994';
-- 철원골 -> 철원골 (서울 서초구 남부순환로356길 61) d=296m
UPDATE restaurants SET lat=37.4821833, lng=127.0386550, kakao_place_id='130446526' WHERE id='53d30ba5-7668-5981-a02d-dda187326312';
-- 치킨영토 -> 치킨영토 양재점 (서울 서초구 남부순환로350길 29-3) d=35m
UPDATE restaurants SET lat=37.4836085, lng=127.0362825, kakao_place_id='2072531633' WHERE id='fcec89c6-6d79-5a26-8768-cc4688d0098b';
-- 카츠공방 -> 카츠공방 양재점 (서울 서초구 강남대로30길 34) d=329m
UPDATE restaurants SET lat=37.4821029, lng=127.0390405, kakao_place_id='1185236896' WHERE id='2e2f2ef0-8ad6-52a0-b6f4-41f0e6ae5b88';
-- 쿠니라멘 -> 쿠니라멘 (서울 서초구 강남대로 224) d=89m
UPDATE restaurants SET lat=37.4841315, lng=127.0350571, kakao_place_id='1838335601' WHERE id='ef07cb42-26da-5165-bb35-478b1ca80ff2';
-- 쿠파 -> 쿠파 (서울 서초구 남부순환로356길 51) d=256m
UPDATE restaurants SET lat=37.4827077, lng=127.0385230, kakao_place_id='717223378' WHERE id='a305a8d2-4146-523e-8ae4-ca729df4ba15';
-- 퀸즈가든 -> 퀸즈가든 (서울 서초구 강남대로53길 7) d=1357m
UPDATE restaurants SET lat=37.4942939, lng=127.0282612, kakao_place_id='27321852' WHERE id='ec7faa13-e2fa-59a2-9ccd-209fb2631014';
-- 태국식당 356 -> 태국식당356 (서울 서초구 남부순환로350길 19-16) d=77m
UPDATE restaurants SET lat=37.4841085, lng=127.0366107, kakao_place_id='957969643' WHERE id='7520fd49-9e05-50d7-bf1f-f157e3ed32d4';
-- 트래키 -> 트래키 (서울 강남구 강남대로42길 23) d=212m
UPDATE restaurants SET lat=37.4856097, lng=127.0359330, kakao_place_id='1063875260' WHERE id='63bc5451-5409-5b8f-95a4-113786346da5';
-- 한양돈까스 -> 한양돈까스 (서울 서초구 양재천로 107-19) d=786m
UPDATE restaurants SET lat=37.4772508, lng=127.0395558, kakao_place_id='1176904318' WHERE id='fa3460a8-1a74-59fd-9e71-11842495c229';
-- 호랑이 초밥 -> 호랑이초밥 양재점 (서울 서초구 남부순환로356길 92) d=417m
UPDATE restaurants SET lat=37.4808136, lng=127.0389178, kakao_place_id='1679708561' WHERE id='4e4bc375-2688-5927-8ce4-0f0119013661';
-- 호앙비엣 -> 호앙비엣 양재역점 (서울 서초구 남부순환로347길 20) d=397m
UPDATE restaurants SET lat=37.4853172, lng=127.0318828, kakao_place_id='1392790108' WHERE id='f82966b1-dcca-5885-9890-082006c9b0bb';
-- 화차이 -> 화차이 (서울 서초구 남부순환로356길 26) d=178m
UPDATE restaurants SET lat=37.4836963, lng=127.0379152, kakao_place_id='872121672' WHERE id='737c20ed-094d-5881-8a81-fbcc752a7ca5';
-- 히노카츠 -> 히노카츠 (서울 강남구 남부순환로359길 14) d=256m
UPDATE restaurants SET lat=37.4859249, lng=127.0366477, kakao_place_id='1371914067' WHERE id='fffb29f4-3b6e-5590-a54b-7bd38aae6993';

-- Unmatched restaurants (kept lat/lng NULL):
-- NOT FOUND: 직송한우공장 (id=71b2d09e-c41a-5a23-918f-ce024b0cdc68)
-- NOT FOUND: 보들설곰탕 (id=a3293d25-619f-559f-a6ee-d99979bdd905)
-- NOT FOUND: 쓰시섬 (id=1909ce7c-98a3-55f0-9a87-205abe071621)
-- NOT FOUND: 양재화로by설화한우 (id=167a1766-0bfd-5b06-9143-b750f91324f0)

COMMIT;
